sudo: required
services:
  - docker
language: bash
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t nargit/rpi-version .
  # test image
  - docker run nargit/rpi-version
  # push image
  - >
    #!/usr/bin/env bash
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      TAG=$(grep "ENV RPI_VERSION" Dockerfile | awk 'NF>1{print $NF}')
      docker tag nargit/rpi-version nargit/rpi-version:$TAG
      docker push nargit/rpi-version:$TAG
      docker push nargit/rpi-version
    fi