name: Tests

on: ["push", "pull_request"]

jobs:
  Multi-OS-Build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-18.04, macos-10.14, windows-2019]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tools
      run: |
        pip install --upgrade pip
        pip install tox
    - name: Run Tests
      run: tox -e py
      #run: tox -e py  # Run tox using the version of Python in `PATH
